config/routes.rb
Rails.application.routes.draw do
  
  post 'my_notes/create'
  get 'my_notes/destroy'
  
  devise_for :users, controllers: {
    #registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }
  
  devise_scope :user do
    get 'accepted' => 'users/registrations#accepted'
  end
 
  get 'toppages/index'
  get 'toppages/rule'
  get 'toppages/form'
  get 'toppages/profile'
  get 'toppages/privacy'
  get 'toppages/commerce'
  post 'toppages/create'
  root to: 'toppages#index'
  
  get 'my_pages/home', to: 'my_pages#home'
  
  resources :notes,only: [:index,:show]

  resources :sales,only: [:index,:show]

  resources :releases, only: [:index,:show]
  
  resources :user_profiles , only: [:new, :create,:show,:edit,:update] do 
    collection do
      get 'get_departments'
    end
  end

  
  resources :lectures ,only: [:new,:create],controller: 'notes/lectures' do
    get 'notes/lectures' ,to: 'notes/lectures#new'
      collection do
      get 'get_departments'
      get 'get_educators'
      get 'get_lectures'
      end
  end

  resources :cards, only: [:new,:show,:create] do
    collection do 
      post 'show'
    end
  end




  resources :images ,only: [:new, :create],controller: 'notes/images' 

  resources :information ,only: [:new, :create],controller: 'notes/information' 
  resources :my_notes, only: [:create , :destroy]

  resources :bank_accounts, only: [:new,:create,:show,:edit,:update]


  #post '/lectures' , to: 'notes/lectures#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bank.rb
class Bank < ApplicationRecord
    has_many :bank_accounts,dependent: :destroy
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord
    belongs_to :user
    belongs_to :bank

    validates :branch ,presence: true
    validates :account ,presence: true
    validates :kind ,presence: true
    validates :sex ,presence: true,format: { with: /\A[A-Z]+\z/}
    validates :name ,presence: true,format: { with: /\A[A-Z]+\z/}

end

app/models/card.rb
class Card < ApplicationRecord
    require 'payjp'
    Payjp.api_key = Rails.application.credentials.dig(:payjp, :ENV['PAYJP_PRIVATE_KEY'])
    belongs_to :user
end

app/models/department.rb
class Department < ApplicationRecord
    has_many :educators_departments
    has_many :educators ,through: :educators_departments
    belongs_to :faculty
    has_many :notes 
    has_many :user_profiles
end

app/models/educator.rb
class Educator < ApplicationRecord
    def full_name
        if self.last_name.present? && self.first_name.present?
        self.last_name + self.first_name
        end
    end
    has_one :educator_position
    has_many :educators_departments
    has_many :departments ,through: :educators_departments
    has_many :lectures_educators
    has_many :lectures ,through: :lectures_educators
end

app/models/faculty.rb
class Faculty < ApplicationRecord
  has_many :departments
end

app/models/image.rb
class Image < ApplicationRecord
    belongs_to :note
    mount_uploader :image, ImageUploader
    validates :image , presence: true
    validates :note_id , presence: true  
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
    validates :name ,presence: true
    validates :email,presence: true
end

app/models/lecture.rb
class Lecture < ApplicationRecord
    has_many :notes
    has_many :lectures_educators
    has_many :educators, through: :lectures_educators
    
    def self.import(file)
        csv_text = File.read(Rails.root + 'app/lecture1.csv', encoding: 'encoding')
        changed_csv_text = csv_text.gsub /^$\n/, ''
        @csv = CSV.parse(changed_csv_text, headers: true)
        @csv.each do |row|
            # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
            lecture = find_by(id: row["id"]) || new
            # CSVからデータを取得し、設定する
            lecture.attributes = row.to_hash.slice(*updatable_attributes)
            # 保存する
            lecture.save
        end
    end

    def self.updatable_attributes
        ["id", "name", "educator_id", "educators_educator_position_id"]
    end
end

app/models/my_note.rb
class MyNote < ApplicationRecord
    belongs_to :buyer, class_name: "User",optional: true, foreign_key: 'buyer_id'
    belongs_to :note
end

app/models/note.rb
class Note < ApplicationRecord
    belongs_to :user
    belongs_to :lecture
    has_many :images,dependent: :destroy
    belongs_to :department
    has_many :my_notes,dependent: :destroy
    has_many :buyers,through: :my_notes,dependent: :destroy
    belongs_to :exhibitor, class_name: 'User', foreign_key: :exhibitor_id
    
    validates :price ,presence: true 
    validates :year ,presence: true
    validates :grade ,presence: true
    validates :exhibitor_id ,presence: true
    validates :department_id ,presence: true
    validates :lecture_id ,presence: true
    
    def buyed?(user)
        self.buyers.include?(user)
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :notes,dependent: :destroy
  has_one :user_profile,dependent: :delete,foreign_key: :user_id
  has_many :my_notes, foreign_key: 'buyer_id',dependent: :destroy
  has_many :notes,through: :my_notes
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable,
         :omniauthable, omniauth_providers: %i[google_oauth2]
  #validate :check_email
  has_many :cards,dependent: :destroy,foreign_key: :user_id
  has_one :bank_account,dependent: :delete,foreign_key: :user_id
 # validates :accepted, presence: {message: 'を入力してください'}
  

  def check_email
    if email !~ /^@eis.hokudai.ac.jp/
      errors.add(:email, " は学校のアドレスを使ってください") 
    end
  end
 
  def buy(note) 
    unless self.id == note.exhibitor_id
      note.my_notes.find_or_create_by(note_id: note.id,buyer_id: self.id)
    end
  end

  protected
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
  
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
    belongs_to :department
    belongs_to :user

    validates :name,presence: true 
    validates :department_id ,presence: true 
    validates :school_year ,presence: true 

end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
    def new
        @profile = current_user.build_user_profile
    end

    def create
        @profile = current_user.build_user_profile
        @profile.name = params[:user_profile][:name]
        @profile.school_year = params[:user_profile][:school_year]
        @profile.department_id = params[:lectures_path][:department_id]
        if
            @profile.save!
            redirect_to root_path
            flash[:notice] = '登録しました'
        else
            redirect_to action: "new"
            flash[:alert] = '登録に失敗しました'
        end
    end

    def get_departments
        render partial: 'get_departments', locals: {faculty_id: params[:faculty]}  
    end

    def show
        unless current_user.user_profile
            @profile = current_user.build_user_profile
            return render :new
        end
        @department = current_user.user_profile.department
        @faculty = @department.faculty
    end

    def edit 
        @profile = UserProfile.find_by(user_id: current_user.id)
    end

    def update
        @profile = UserProfile.find_by(user_id: current_user.id)
        @profile.name = params[:user_profile][:name]
        @profile.school_year = params[:user_profile][:school_year]
        @profile.department_id = params[:lectures_path][:department_id]
        if @profile.update(profile_params)
            flash[:success] = 'プロフィールを更新しました'
            redirect_to user_profile_path(id: @profile.id)
        else
            flash.now[:danger] = 'プロフィールを更新できません'
            render :edit
        end
    end

    private
    def profile_params
        params.require(:user_profile).permit(:name,:school_year,:lectures_path =>[:department_id])
    end

end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/helpers/my_notes_helper.rb
module MyNotesHelper
end

app/helpers/my_pages_helper.rb
module MyPagesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/release_helper.rb
module ReleaseHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/views/user_profiles/_get_departments.html.erb
<%= label :department, "学科" %><br>
<%= collection_select :lectures_path ,:department_id, Department.where(faculty_id: faculty_id), :id, :name,{prompt: "選択して下さい"} %>

app/views/user_profiles/edit.html.erb
<div class="text-center p-4">
  <h3>プロフィール編集ページ</h3>
</div>
<div class="row pr-5 pl-5">
  <div class="offset-sm-4 col-sm-4">

    <%= form_with(model: @profile,url: {controller: 'user_profiles', action: 'update' },method: :put,  local: true) do |f| %>
      
      <div class="form-group text-center">
        <%= f.label :name, 'ニックネーム' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group text-center">
        <%= f.label :school_year, '学年' %>
        <%= f.number_field :school_year, class: 'form-control' %>
      </div>

      <div class = 'faculty text-center'> 
        <%= f.label :faculty, "学部"%></br>
        <%= f.collection_select :faculty, Faculty.all, :id, :name,{prompt: "選択して下さい"} %>
      </div>

      <div class = 'get_departments text-center pb-5 pt-3'>
        <%= render partial: 'get_departments', locals: {faculty_id: Faculty.first.id } %>
      </div>

      <div class="pb-5">
      <%= f.submit '更新', class: 'btn btn-info btn-block' %>
      </div>
    <% end %>
  </div>
</div>

app/views/user_profiles/new.html.erb
<div class="text-center pt-4">
  <h2>プロフィール</h2>
</div>

<div class="row pl-5 pr-5 pt-3">
  <div class="offset-sm-4 col-sm-4 text-center">

    <%= form_with(model: @profile,url: user_profiles_path,method: :post,  local: true) do |f| %>
      
      <div class="form-group">
        <%= f.label :name, 'ニックネーム' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :school_year, '学年' %>
        <%= f.number_field :school_year, class: 'form-control' %>
      </div>

      <div class = 'faculty'> 
        <%= f.label :faculty, "学部"%></br>
        <%= f.collection_select :faculty, Faculty.all, :id, :name,{prompt: "選択して下さい"} %>
      </div>

      <div class = 'get_departments mt-3'>
        <%= render partial: 'get_departments', locals: {faculty_id: Faculty.first.id } %>
      </div>

     
      <%= f.submit '登録', class: 'btn btn-info btn-block mt-5 mb-5' %>
    <% end %>
  </div>
</div>

app/views/user_profiles/show.html.erb
<div class="text-center pt-4">
  <h2>プロフィール</h2>
</div>
<div class="row pl-5 pr-5 pt-3">
  <div class="col-sm-6 offset-sm-3 bg-light">
    <div class="mb-1 pt-3 ">
    <label>ニックネーム</label>:
        <%= current_user.user_profile.name%>
    </div>
    
    <div class="mb-1">
    <label>学部</label>:
        <%= @faculty.name %>
    </div>
    <div class="mb-1">
    <label>学科</label>:
        <%= @department.name%>
    </div>
    <div class="mb-1">
        <label>学年</label>:
        <%= current_user.user_profile.school_year %>
    </div>
    <div class="mb-1">
    <label>email</label>:
        <%= current_user.email %>
    </div>
    <div class="mb-3">
        <%= %>
    </div>

  </div>
</div>
<div class="text-center pt-4 pb-4">
  <%= link_to '編集', edit_user_profile_path%>
</div>