config/routes.rb
Rails.application.routes.draw do
  
  post 'my_notes/create'
  get 'my_notes/destroy'
  
  devise_for :users, controllers: {
    #registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }
  
  devise_scope :user do
    get 'accepted' => 'users/registrations#accepted'
  end
 
  get 'toppages/index'
  get 'toppages/rule'
  get 'toppages/form'
  get 'toppages/profile'
  get 'toppages/privacy'
  get 'toppages/commerce'
  post 'toppages/create'
  root to: 'toppages#index'
  
  get 'my_pages/home', to: 'my_pages#home'
  
  resources :notes,only: [:index,:show]

  resources :sales,only: [:index,:show]

  resources :releases, only: [:index,:show]
  
  resources :user_profiles , only: [:new, :create,:show,:edit,:update] do 
    collection do
      get 'get_departments'
    end
  end

  
  resources :lectures ,only: [:new,:create],controller: 'notes/lectures' do
    get 'notes/lectures' ,to: 'notes/lectures#new'
      collection do
      get 'get_departments'
      get 'get_educators'
      get 'get_lectures'
      end
  end

  resources :cards, only: [:new,:show,:create] do
    collection do 
      post 'show'
    end
  end




  resources :images ,only: [:new, :create],controller: 'notes/images' 

  resources :information ,only: [:new, :create],controller: 'notes/information' 
  resources :my_notes, only: [:create , :destroy]

  resources :bank_accounts, only: [:new,:create,:show,:edit,:update]


  #post '/lectures' , to: 'notes/lectures#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bank.rb
class Bank < ApplicationRecord
    has_many :bank_accounts,dependent: :destroy
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord
    belongs_to :user
    belongs_to :bank

    validates :branch ,presence: true
    validates :account ,presence: true
    validates :kind ,presence: true
    validates :sex ,presence: true,format: { with: /\A[A-Z]+\z/}
    validates :name ,presence: true,format: { with: /\A[A-Z]+\z/}

end

app/models/card.rb
class Card < ApplicationRecord
    require 'payjp'
    Payjp.api_key = Rails.application.credentials.dig(:payjp, :ENV['PAYJP_PRIVATE_KEY'])
    belongs_to :user
end

app/models/department.rb
class Department < ApplicationRecord
    has_many :educators_departments
    has_many :educators ,through: :educators_departments
    belongs_to :faculty
    has_many :notes 
    has_many :user_profiles
end

app/models/educator.rb
class Educator < ApplicationRecord
    def full_name
        if self.last_name.present? && self.first_name.present?
        self.last_name + self.first_name
        end
    end
    has_one :educator_position
    has_many :educators_departments
    has_many :departments ,through: :educators_departments
    has_many :lectures_educators
    has_many :lectures ,through: :lectures_educators
end

app/models/faculty.rb
class Faculty < ApplicationRecord
  has_many :departments
end

app/models/image.rb
class Image < ApplicationRecord
    belongs_to :note
    mount_uploader :image, ImageUploader
    validates :image , presence: true
    validates :note_id , presence: true  
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
    validates :name ,presence: true
    validates :email,presence: true
end

app/models/lecture.rb
class Lecture < ApplicationRecord
    has_many :notes
    has_many :lectures_educators
    has_many :educators, through: :lectures_educators
    
    def self.import(file)
        csv_text = File.read(Rails.root + 'app/lecture1.csv', encoding: 'encoding')
        changed_csv_text = csv_text.gsub /^$\n/, ''
        @csv = CSV.parse(changed_csv_text, headers: true)
        @csv.each do |row|
            # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
            lecture = find_by(id: row["id"]) || new
            # CSVからデータを取得し、設定する
            lecture.attributes = row.to_hash.slice(*updatable_attributes)
            # 保存する
            lecture.save
        end
    end

    def self.updatable_attributes
        ["id", "name", "educator_id", "educators_educator_position_id"]
    end
end

app/models/my_note.rb
class MyNote < ApplicationRecord
    belongs_to :buyer, class_name: "User",optional: true, foreign_key: 'buyer_id'
    belongs_to :note
end

app/models/note.rb
class Note < ApplicationRecord
    belongs_to :user
    belongs_to :lecture
    has_many :images,dependent: :destroy
    belongs_to :department
    has_many :my_notes,dependent: :destroy
    has_many :buyers,through: :my_notes,dependent: :destroy
    belongs_to :exhibitor, class_name: 'User', foreign_key: :exhibitor_id
    
    validates :price ,presence: true 
    validates :year ,presence: true
    validates :grade ,presence: true
    validates :exhibitor_id ,presence: true
    validates :department_id ,presence: true
    validates :lecture_id ,presence: true
    
    def buyed?(user)
        self.buyers.include?(user)
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :notes,dependent: :destroy
  has_one :user_profile,dependent: :delete,foreign_key: :user_id
  has_many :my_notes, foreign_key: 'buyer_id',dependent: :destroy
  has_many :notes,through: :my_notes
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable,
         :omniauthable, omniauth_providers: %i[google_oauth2]
  #validate :check_email
  has_many :cards,dependent: :destroy,foreign_key: :user_id
  has_one :bank_account,dependent: :delete,foreign_key: :user_id
 # validates :accepted, presence: {message: 'を入力してください'}
  

  def check_email
    if email !~ /^@eis.hokudai.ac.jp/
      errors.add(:email, " は学校のアドレスを使ってください") 
    end
  end
 
  def buy(note) 
    unless self.id == note.exhibitor_id
      note.my_notes.find_or_create_by(note_id: note.id,buyer_id: self.id)
    end
  end

  protected
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
  
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
    belongs_to :department
    belongs_to :user

    validates :name,presence: true 
    validates :department_id ,presence: true 
    validates :school_year ,presence: true 

end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    @notes = Note.last(3)
  end

  def rule
  end

  def form
    @inquiry = Inquiry.new
  end

  def create
    @inquiry = Inquiry.new
    @inquiry.name = params[:inquiry][:name]
    @inquiry.email = params[:inquiry][:email]
    @inquiry.message = params[:inquiry][:message]

    if @inquiry.save
      InquiryMailer.send_mail(@inquiry).deliver_now
      redirect_to toppages_index_path
      flash[:success] = 'お問い合わせを送信しました！'
      
    else
      render action: "form"
      flash.now[:alert] = 'お問い合わせに失敗しました'
    end
  end

  def profile
  end

  def privacy
  end

  def commerce
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/helpers/my_notes_helper.rb
module MyNotesHelper
end

app/helpers/my_pages_helper.rb
module MyPagesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/release_helper.rb
module ReleaseHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/views/toppages/commerce.html.erb
<div class="bg-light">
<h3 class="text-center pt-5 pb-5">特定商取引法に基づく表記</h3>
<table class="table p-4">
<tbody class="pb-5">
    <tr>
        <th>アプリ名</th>
        <td>hokudainote</td>
    </tr>
    <tr>
        <th>販売事業者名</th>
        <td>杉山堅志郎</td>
    </tr>
    <tr>
        <th>代表者名</th>
        <td>杉山堅志郎</td>
    </tr>
    <tr>
        <th>所在地</th>
        <td>〒001－0020<br>北海道札幌市北区北２０条西７丁目２－３３</td>
    </tr>
    <tr>
        <th>お問い合わせ</th>
        <td><%= link_to 'こちら' ,toppages_form_path	%>からお問い合わせください。<br>
            ※代表者電話番号はお客様からのご要望に基づき遅滞なく電子メールにて通知いたします。<br> 代表者電話番号が必要なお客様は上記フォームよりお申し出ください。
        </td>
    </tr>
    <tr>
        <th>販売価格</th>
        <td>購入手続きの際に画面に表示されます。<br>消費税は内税として表示しております。</td>
    </tr>
    <tr>
        <th>販売価格以外で<br>お客様に発生する金銭</th>
        <td>当サイトのページの閲覧、コンテンツ購入、ソフトウェアのダウンロード等に必要となるインターネット接続料金、通信料金は、お客様のご負担となります。</td>
    </tr>
    <tr>
        <th>お支払方法</th>
        <td>以下のお支払方法をご利用いただけます。<br>・各種クレジットカード</td>
    </tr>
    <tr>
        <th>商品購入方法</th>
        <td>
	    ノートの詳細ページから「購入」ボタンを押下し、各種お支払方法で決済していただきますと、マイページのノート管理より閲覧が可能になります。
        </td>
    </tr>
    <tr>
        <th>デジタルアイテム等の利用が可能となる時期</th>
        <td>
	    特別な定めを置いている場合を除き、お支払い手続き完了後直ちにご利用いただけます。
        </td>
    </tr>
    <tr>
        <th>動作環境</th>
        <td>
        動作環境については、本サービスのウェブサイトをご確認ください。
        </td>
    </tr>
    <tr>
        <th>返品・キャンセル</th>
        <td>
        １.お客様のご都合による返品・キャンセル<br>
        商品の性質上、各アプリケーションご購入後の返金・返品はできかねます。<br>
        ２.アプリケーションの瑕疵に基づく返品（キャンセル）<br>
        アプリケーションに瑕疵が発見されたときは、瑕疵を修補したアプリケーションをアプリケーションのバージョンアップ又はその他適切な方法で提供いたします。<br>
        </td>
    </tr>
    <tr>
        <th>特別条件</th>
        <td>
        ・クーリングオフについて<br>
        特定商取引法に規定されているクーリングオフが適用されるサービスではありません。<br><br>
        </td>
    </tr> 
</tbody>
</table>
</div>

app/views/toppages/form.html.erb
<h3 class="text-center pt-5 pb-3">お問い合わせ</h3>
<div class="text-center pl-5 pr-5 mb-3">
お問い合わせは<br><br>
    <i class="fa fa-envelope"></i> ken4600223@gmail.com<br>
    <i class="fab fa-twitter"></i> <a href="https://twitter.com/hokudainote">hokudainote</a><br><br>
もしくは以下のフォームよりお願いいたします。
</div>

<div class="form-group pl-5 pr-5">
    <%= form_with(model: @inquiry, url: toppages_create_path,method: :post ,local: true) do |f| %>
    <%= render 'layouts/error_messages',model: f.object %>
    <div class="field text-center p-3 offset-sm-4 col-sm-4">
        <%= f.label :name, '名前（必須）' %><br/>
        <%= f.text_field :name,class: "form-control" %>
    </div>

    <div class="field text-center p-3 offset-sm-4 col-sm-4">
        <%= f.label :email, 'メールアドレス（必須）' %><br />
        <%= f.email_field :email,class: "form-control" %>
    </div>

    <div class="field text-center p-3 offset-sm-4 col-sm-4">
        <%= f.label :message , 'メッセージ本文'%><br />
        <%= f.text_field :message,class: "form-control" %>
    </div>
    <div class="field text-center p-3 offset-sm-5 col-sm-2">
    <%= f.submit '送信', class: 'btn btn-info btn-block mt-5 mb-5' %>
    </div>
    <% end %>
</div>



app/views/toppages/index.html.erb
<h1 class="text-center pt-5 pr-5 pl-5 pb-3">hokudainote</h1>

<%# <a href="https://lin.ee/0R5Ofx2"><img src="https://scdn.line-apps.com/n/line_add_friends/btn/ja.png" alt="友だち追加" height="36" border="0"></a> %>

<% unless user_signed_in? %>
<div class="p-4">
    <div class="text-center mb-5" >
    hokudainote は
    北大生限定の講義ノートを個人が販売・購入できるプラットフォームです<br>
    （決済手数料１０％）<br><br>
    <%= image_tag 'e.png',alt: 'hokudainoteとは',class: 'img-fluid' %>
    </div>
    <br>
    <div class="text-center mb-3">
        <%= image_tag 'hokudainote.png',alt: '１度出品したら一生の資産に',class: 'img-fluid'%>
        <br><br>例　大学２年時に出品した場合
    </div>
    <%# <div class="text-center pl-4 pr-4 mb-3">
        <%= link_to 'ノートを見てみる',notes_path,class: "btn btn-info "%>
    <%# </div> %>
    <div class="text-center py-4">
        <div class="pb-3">新着ノート</div>
        <%= render 'notes/notes', notes: @notes %>
    </div>
    <div class="text-center pl-4 pr-4 mb-3">
        <%= link_to '新規登録',new_user_registration_path,class: "btn btn-info "%>
    </div>
    <div class="text-center pl-4 pr-4 mb-3">
        <%= link_to 'ログイン',new_user_session_path,class: "btn btn-info "%>
    </div>
</div>
<% else %>        
    <div class="text-center">
        <div class="p-0 m-3 mt-3">
            <%= link_to 'ノートを買う', '/notes#index', class: 'btn btn-info a'  %>
        </div>
        <div class="p-0 m-3">
            <%= link_to 'ノートを売る', new_lecture_path, class: 'btn btn-info a'  %>
        </div>
        <div class="p-0 m-3">
            <%= link_to ' マイページ ', my_pages_home_path, class: 'btn btn-info'  %> 
        </div>
        <div class="p-0 mb-4 m-3">
            <%= link_to ' ログアウト ', destroy_user_session_path,method: :delete , class: 'btn btn-danger'  %>
        </div>
        <br><br>
    </div>
<% end %>

app/views/toppages/privacy.html.erb
<div class="bg-light">
<h3 class="text-center pt-4">プライバシーポリシー</h3>
<div class="p-5">
運営者は，本ウェブサイト上で提供するサービス「hokudainote」（以下,「本サービス」といいます。）における，ユーザーの個人情報の取扱いについて，以下のとおりプライバシーポリシー（以下，「本ポリシー」といいます。）を定めます。<br>
<br>
第1条（個人情報）<br>
「個人情報」とは，個人情報保護法にいう「個人情報」を指すものとし，生存する個人に関する情報であって，当該情報に含まれる氏名，生年月日，住所，電話番号，連絡先その他の記述等により特定の個人を識別できる情報及び容貌，指紋，声紋にかかるデータ，及び健康保険証の保険者番号などの当該情報単体から特定の個人を識別できる情報（個人識別情報）を指します。<br>
<br>
第2条（個人情報の収集方法）<br>
運営者は，ユーザーが利用登録をする際に氏名，生年月日，住所，電話番号，メールアドレス，銀行口座番号，クレジットカード番号，運転免許証番号などの個人情報をお尋ねすることがあります。また，ユーザーと提携先などとの間でなされたユーザーの個人情報を含む取引記録や決済に関する情報を,運営者の提携先（情報提供元，広告主，広告配信先などを含みます。以下，｢提携先｣といいます。）などから収集することがあります。<br>
<br>
第3条（個人情報を収集・利用する目的）<br>
運営者が個人情報を収集・利用する目的は，以下のとおりです。<br>
<br>
運営者サービスの提供・運営のため<br>
ユーザーからのお問い合わせに回答するため（本人確認を行うことを含む）<br>
ユーザーが利用中のサービスの新機能，更新情報，キャンペーン等及び運営者が提供する他のサービスの案内のメールを送付するため<br>
メンテナンス，重要なお知らせなど必要に応じたご連絡のため<br>
利用規約に違反したユーザーや，不正・不当な目的でサービスを利用しようとするユーザーの特定をし，ご利用をお断りするため<br>
ユーザーにご自身の登録情報の閲覧や変更，削除，ご利用状況の閲覧を行っていただくため<br>
有料サービスにおいて，ユーザーに利用料金を請求するため<br>
上記の利用目的に付随する目的<br>
第4条（利用目的の変更）<br>
運営者は，利用目的が変更前と関連性を有すると合理的に認められる場合に限り，個人情報の利用目的を変更するものとします。<br>
利用目的の変更を行った場合には，変更後の目的について，運営者所定の方法により，ユーザーに通知し，または本ウェブサイト上に公表するものとします。<br>
第5条（個人情報の第三者提供）<br>
運営者は，次に掲げる場合を除いて，あらかじめユーザーの同意を得ることなく，第三者に個人情報を提供することはありません。ただし，個人情報保護法その他の法令で認められる場合を除きます。<br>
人の生命，身体または財産の保護のために必要がある場合であって，本人の同意を得ることが困難であるとき<br>
公衆衛生の向上または児童の健全な育成の推進のために特に必要がある場合であって，本人の同意を得ることが困難であるとき<br>
国の機関もしくは地方公共団体またはその委託を受けた者が法令の定める事務を遂行することに対して協力する必要がある場合であって，本人の同意を得ることにより当該事務の遂行に支障を及ぼすおそれがあるとき<br>
予め次の事項を告知あるいは公表し，かつ運営者が個人情報保護委員会に届出をしたとき<br>
利用目的に第三者への提供を含むこと<br>
第三者に提供されるデータの項目<br>
第三者への提供の手段または方法<br>
本人の求めに応じて個人情報の第三者への提供を停止すること<br>
本人の求めを受け付ける方法<br>
前項の定めにかかわらず，次に掲げる場合には，当該情報の提供先は第三者に該当しないものとします。<br>
運営者が利用目的の達成に必要な範囲内において個人情報の取扱いの全部または一部を委託する場合<br>
合併その他の事由による事業の承継に伴って個人情報が提供される場合<br>
個人情報を特定の者との間で共同して利用する場合であって，その旨並びに共同して利用される個人情報の項目，共同して利用する者の範囲，利用する者の利用目的および当該個人情報の管理について責任を有する者の氏名または名称について，あらかじめ本人に通知し，または本人が容易に知り得る状態に置いた場合<br>
第6条（個人情報の開示）<br>
運営者は，本人から個人情報の開示を求められたときは，本人に対し，遅滞なくこれを開示します。ただし，開示することにより次のいずれかに該当する場合は，その全部または一部を開示しないこともあり，開示しない決定をした場合には，その旨を遅滞なく通知します。なお，個人情報の開示に際しては，1件あたり1，000円の手数料を申し受けます。<br>
本人または第三者の生命，身体，財産その他の権利利益を害するおそれがある場合<br>
運営者の業務の適正な実施に著しい支障を及ぼすおそれがある場合<br>
その他法令に違反することとなる場合<br>
前項の定めにかかわらず，履歴情報および特性情報などの個人情報以外の情報については，原則として開示いたしません。<br>
第7条（個人情報の訂正および削除）<br>
ユーザーは，運営者の保有する自己の個人情報が誤った情報である場合には，運営者が定める手続きにより，運営者に対して個人情報の訂正，追加または削除（以下，「訂正等」といいます。）を請求することができます。<br>
運営者は，ユーザーから前項の請求を受けてその請求に応じる必要があると判断した場合には，遅滞なく，当該個人情報の訂正等を行うものとします。<br>
運営者は，前項の規定に基づき訂正等を行った場合，または訂正等を行わない旨の決定をしたときは遅滞なく，これをユーザーに通知します。<br>
第8条（個人情報の利用停止等）<br>
運営者は，本人から，個人情報が，利用目的の範囲を超えて取り扱われているという理由，または不正の手段により取得されたものであるという理由により，その利用の停止または消去（以下，「利用停止等」といいます。）を求められた場合には，遅滞なく必要な調査を行います。<br>
前項の調査結果に基づき，その請求に応じる必要があると判断した場合には，遅滞なく，当該個人情報の利用停止等を行います。<br>
運営者は，前項の規定に基づき利用停止等を行った場合，または利用停止等を行わない旨の決定をしたときは，遅滞なく，これをユーザーに通知します。<br>
前2項にかかわらず，利用停止等に多額の費用を有する場合その他利用停止等を行うことが困難な場合であって，ユーザーの権利利益を保護するために必要なこれに代わるべき措置をとれる場合は，この代替策を講じるものとします。<br>
第9条（プライバシーポリシーの変更）<br>
本ポリシーの内容は，法令その他本ポリシーに別段の定めのある事項を除いて，ユーザーに通知することなく，変更することができるものとします。<br>
運営者が別途定める場合を除いて，変更後のプライバシーポリシーは，本ウェブサイトに掲載したときから効力を生じるものとします。<br>
第10条（お問い合わせ窓口）<br>
本ポリシーに関するお問い合わせは，<%= link_to 'こちら',toppages_form_path %>からお願いいたします。<br>
<br>
以上
</div>
</div>

app/views/toppages/profile.html.erb
<h3 class="text-center pt-4">運営者情報</h3>
<div class="text-center p-5">
杉山堅志郎<br>北海道大学工学部3年<br><br>
半年ほど前からこのサービスの開発を進めてきました。<br>
言語はRuby、フレームワークはrailsを使っています。<br><br>
現在一人で開発をしているため、一緒に開発を進められる仲間を募集しています。<br>railsを使ったアプリ開発をした経験のある方がいましたら、ぜひ手伝っていただきたいです。<br>
連絡お待ちしています。
</div>
<br>