config/routes.rb
Rails.application.routes.draw do
  
  post 'my_notes/create'
  get 'my_notes/destroy'
  
  devise_for :users, controllers: {
    #registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }
  
  devise_scope :user do
    get 'accepted' => 'users/registrations#accepted'
  end
 
  get 'toppages/index'
  get 'toppages/rule'
  get 'toppages/form'
  get 'toppages/profile'
  get 'toppages/privacy'
  get 'toppages/commerce'
  post 'toppages/create'
  root to: 'toppages#index'
  
  get 'my_pages/home', to: 'my_pages#home'
  
  resources :notes,only: [:index,:show]

  resources :sales,only: [:index,:show]

  resources :releases, only: [:index,:show]
  
  resources :user_profiles , only: [:new, :create,:show,:edit,:update] do 
    collection do
      get 'get_departments'
    end
  end

  
  resources :lectures ,only: [:new,:create],controller: 'notes/lectures' do
    get 'notes/lectures' ,to: 'notes/lectures#new'
      collection do
      get 'get_departments'
      get 'get_educators'
      get 'get_lectures'
      end
  end

  resources :cards, only: [:new,:show,:create] do
    collection do 
      post 'show'
    end
  end




  resources :images ,only: [:new, :create],controller: 'notes/images' 

  resources :information ,only: [:new, :create],controller: 'notes/information' 
  resources :my_notes, only: [:create , :destroy]

  resources :bank_accounts, only: [:new,:create,:show,:edit,:update]


  #post '/lectures' , to: 'notes/lectures#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord
    belongs_to :user
    belongs_to :bank

    validates :branch ,presence: true
    validates :account ,presence: true
    validates :kind ,presence: true
    validates :sex ,presence: true,format: { with: /\A[A-Z]+\z/}
    validates :name ,presence: true,format: { with: /\A[A-Z]+\z/}

end

app/controllers/bank_accounts_controller.rb
class BankAccountsController < ApplicationController
    def new
        @account = current_user.build_bank_account
    end

    def create
        @account = current_user.build_bank_account
        @account.bank_id = params[:bank_account][:bank_id]
        @account.branch=params[:bank_account][:branch]
        @account.account=params[:bank_account][:account]        
        @account.kind=params[:bank_account][:kind]
        @account.sex=params[:bank_account][:sex]
        @account.name=params[:bank_account][:name]


        if
            #Bank.find(params[:bank_account][:bank_id]).bank_accounts.create
            @account.save!
            
            redirect_to my_pages_home_path
            flash[:success] = '口座を登録しました'
        else
            render action: "new"
            flash.now[:alert] = '口座登録に失敗しました'
        end
    end

    def show
        @account = BankAccount.find_by(user_id: current_user.id)
    end

    def edit
        @account = BankAccount.find_by(user_id: current_user.id) 
    end

    def update
        @account = BankAccount.find_by(user_id: current_user.id) 
        @account.bank_id = params[:bank_account][:bank_id]
        @account.branch=params[:bank_account][:branch]
        @account.account=params[:bank_account][:account]        
        @account.kind=params[:bank_account][:kind]
        @account.sex=params[:bank_account][:sex]
        @account.name=params[:bank_account][:name]

        if
            #Bank.find(params[:bank_account][:bank_id]).bank_accounts.create
            @account.update(account_params)
            
            redirect_to my_pages_home_path
            flash[:success] = '口座を更新しました'
        else
            render action: "edit"
            flash.now[:alert] = '更新に失敗しました'
        end
    end

    private
    def account_params
        params.require(:bank_account).permit(:bank_id,:branch,:account,:kind,:sex,:name)
    end
end

app/helpers/bank_accounts_helper.rb
module BankAccountsHelper
end

app/views/bank_accounts/edit.html.erb
<div class="text-center pt-4">
  <h2>口座編集</h2>
</div>

<div class="row pt-4 ml-5 mr-5">
  <div class="offset-sm-4 col-sm-4 ">

    <%= form_with(model: @account,url: {controller: 'bank_accounts', action: 'update' },method: :put,  local: true) do |f| %>
      <%= render 'layouts/error_messages', model: @account %>
      <div class="form-group">
        <%= f.label :bank_id, '銀行名' %>
        <%= f.collection_select :bank_id, Bank.all, :id, :name,{prompt: "選択して下さい"} %>
      </div>
      
      <div class="form-group">
        <%= f.label :branch, '支店番号' %>
        <%= f.number_field :branch, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :account, '口座番号' %>
        <%= f.number_field :account, class: 'form-control' %>
      </div>

      <div class = 'form-group'> 
        <%= f.label :kind, "口座種別"%></br>
        <%= f.select :kind,['普通'],{prompt: "選択して下さい"}, class: 'form-control'%>
      </div>

      <div class="form-group">
        <%= f.label :sex, '性(半角大文字)' %>
        <%= f.text_field :sex, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :name, '名(半角大文字)' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
     
      <%= f.submit '更新', class: 'btn btn-info btn-block mt-5 mb-5' %>
    <% end %>
  </div>
</div>

app/views/bank_accounts/new.html.erb
<div class="text-center pt-5">
  <h2>口座登録</h2>
</div>

<div class="row pt-4">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @account,url: bank_accounts_path,method: :post,  local: true) do |f| %>
      <%= render 'layouts/error_messages', model: @account %>
      <div class="form-group text-center">
        <%= f.label :bank_id, '銀行名' %><br>
        <%= f.collection_select :bank_id, Bank.all, :id, :name,{prompt: "選択して下さい"} %>
      </div>
      
      <div class="form-group text-center ml-5 mr-5">
        <%= f.label :branch, '支店番号' %>
        <%= f.number_field :branch, class: 'form-control' %>
      </div>

      <div class="form-group text-center ml-5 mr-5">
        <%= f.label :account, '口座番号' %>
        <%= f.number_field :account, class: 'form-control' %>
      </div>

      <div class = 'form-group text-center ml-5 mr-5'> 
        <%= f.label :kind, "口座種別"%></br>
        <%= f.select :kind,['普通'],{prompt: "選択して下さい"}, class: 'form-control'%>
      </div>

      <div class="form-group text-center ml-5 mr-5">
        <%= f.label :sex, '性(半角大文字)' %>
        <%= f.text_field :sex, class: 'form-control',placeholder: 'HOKUDAI' %>
      </div>
      <div class="form-group text-center ml-5 mr-5">
        <%= f.label :name, '名(半角大文字)' %>
        <%= f.text_field :name, class: 'form-control',placeholder: 'NOTE' %>
      </div>
     
      <div class="offset-sm-5 col-sm-2 ">
      <%= f.submit '登録', class: 'btn btn-info btn-block mt-5 mb-5' %>
      </div>
    <% end %>
  </div>
</div>

app/views/bank_accounts/show.html.erb
<div class="text-center pt-5">
  <h2>銀行口座</h2>
</div>
<div class="row mt-4 ml-4 mr-4">
  <div class="offset-sm-4 col-sm-4 ">
    <div class = 'card card-body bg-light'>
        <div>
        <label>銀行名</label>
        <%= Bank.find(@account.bank_id).name %>
        </div>
        <div>
        <label>支店番号</label>
        <%= @account.branch %>
        </div> 
        <div>
        <label>口座番号</label>
        <%= @account.account %>
        </div>         
        <div>
        <label>口座種別</label>
        <%= @account.kind %>
        </div>  
        <div>
        <label>性</label>
        <%= @account.sex %>
        </div> 
        <div>
        <label>名</label>
        <%= @account.name %>
        </div>  

    </div>
    <div class="text-center mt-4 mb-4">
        <%= link_to '編集', edit_bank_account_path%>
    </div>
  </div>
</div>